export const gameDesignCases = [
  {
    number: '01',
    slug: 'swinging-bridge',
    game: 'Homescapes',
    title: 'Swinging Bridge',
    subtitle: 'Win streak, tension & perceived fairness',
    problem: 'A seven-win streak amplifies small differences in level difficulty. A late loss, uncertain shared reward and 30-minute retry gate can make failure feel arbitrary.',
    solution: 'Introduce one Safety Rope at step four. It protects the streak from the next loss while keeping the retry wait, the seven-win goal and the event tension intact.',
    contribution: 'Mapped the event loop, modelled streak probability, formed four fairness hypotheses, designed the recovery mechanic and defined an A/B test with monetisation guardrails.',
    pdf: '/game-design/homescapes-swinging-bridge.pdf',
  },
  {
    number: '02',
    slug: 'make-it-yours',
    game: 'Homescapes',
    title: 'Make It Yours',
    subtitle: 'Optional furniture customisation',
    problem: 'Decoration-minded players may want more authorship than ready-made furniture styles provide, but adding options can slow the renovation flow and create choice overload.',
    solution: 'Keep presets as the fast path and add an optional customisation route for shape, colour and pattern, starting with a deliberately small one-room MVP.',
    contribution: 'Designed the interaction and player journey, scoped three items with curated combinations, and created a usability study plus controlled live-test plan.',
    pdf: '/game-design/homescapes-make-it-yours.pdf',
  },
  {
    number: '03',
    slug: 'flexible-orders',
    game: 'Township',
    title: 'Flexible Orders',
    subtitle: 'Helicopter orders & player choice',
    problem: 'The same goods may be needed by helicopter and train orders, so an order that looks valuable can work against the player’s current town goal.',
    solution: 'Let selected ordinary helicopter orders offer two fixed ingredient alternatives with rewards shown upfront, giving players agency without introducing free rerolls.',
    contribution: 'Reviewed the production and order loop, framed the opportunity cost, developed the feature concept and balance rules, and edited a test plan with economy and retention guardrails.',
    pdf: '/game-design/township-flexible-orders.pdf',
  },
  {
    number: '04',
    slug: 'pull-pin-puzzle',
    game: 'Original level concept',
    title: 'Pull-Pin Puzzle',
    subtitle: 'Timing & irreversible choices',
    problem: 'Both paths begin from the same state, but releasing the bombs too early spends the only obstacle-clearing resource and leaves both coin groups trapped.',
    solution: 'Make the player clear the route first, use a reusable blue pin to guide the bombs into the locked barrier, then reuse it to stage and release the coins.',
    contribution: 'Designed the original level concept, defined its single-use, reusable and bomb-locked elements, and mapped a four-step failure path against a six-step success path.',
    pdf: '/game-design/pull-pin-puzzle.pdf',
  },
]
